Merged Steve and Marcelo's stuff together

diff --git a/install_percona b/install_percona
--- a/install_percona
+++ b/install_percona
@@ -1,9 +1,16 @@
 #!/bin/bash
 
+#########################################
+# Global Variables
+#########################################
+declare START_TIMEOUT=120 # Timeout to wait for PS or PXC to start
+declare SUDO=sudo # Used to check if sudo is installed or if we are running as root
+declare PACKAGES_TO_INSTALL= # List of packages to install
+declare VAR_MODE=ps # Which package the script will install
+declare VAR_MODE_STRING="Percona Server" # Full string name of package the script will install
+declare logfile="install.log"
 
-logfile="install.log"
-START_TIMEOUT=120
-# Check if sudo is installed or if we are running as root
+
 
 #######################################
 # Show script usage info.       
@@ -13,10 +20,11 @@ usage() {
 Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v] [-i] [-b]
 This tool is used to take online backups and can be used to restore a backup as well.
 Available options:      
--h, --help          Print this help and exit
--v, --verbose       Print script debug info 
--i, --interactive   Run the script interactively to prompt the user for configuration values (not implemented)
--b, --backup	    Install Percona XtraBackup package in addition to database server
+-h, --help				Print this help and exit
+-v, --verbose			Print script debug info 
+-m, --mode [ps|pxc]		Which database server the script will install. Default ps"
+-i, --interactive		Run the script interactively to prompt the user for configuration values (not implemented)
+-b, --backup			Install Percona XtraBackup package in addition to database server
 EOF
   exit                  
 }                       
@@ -29,6 +37,15 @@ parse_params() {
     case "${1-}" in
     -h | --help) usage ;;
     -v | --verbose) set -x ;;
+	-m | --mode)
+        VAR_MODE="$2"
+        if [[ ! $VAR_MODE =~ ^(ps|pxc)$ ]]; then
+          echo "[Error] Invalid --mode passed: '$VAR_MODE'"
+          echo "Please choose one of these modes: ps or pxc"
+          exit 1
+        fi
+        shift 2
+        ;;
 #    -i | --interactive) interactive=1 ;;
     -b | --backup) install_backup=true
       shift
@@ -99,6 +116,8 @@ die() {
   exit "${code}"
 }
 
+
+
 #########################################
 # Install PXB
 #########################################
@@ -112,93 +131,115 @@ install_pxb() {
 
 }
 
+##########################################
+# Install Percona Repository and define 
+# service name
+##########################################
+
+function install_repo_and_define_service()
+{
+  if check_command yum ; then
+     if [ ! -f /usr/bin/sudo ]; then
+      if [[ $(id -u) -eq 0 ]]; then
+        SUDO=""
+      else
+        yum install -y sudo
+      fi
+    fi
+
+	run_root "yum install -y https://repo.percona.com/yum/percona-release-latest.noarch.rpm which"
+    # Disable mysql module
+    if check_command dnf
+    then
+      run_root "dnf module disable -y mysql"
+    fi
+  else
+    if [ ! -f /usr/bin/sudo ]; then
+      if [[ $(id -u) -eq 0 ]];
+      then
+        SUDO=""
+      else
+        apt update
+        apt install -y sudo
+      fi
+    fi
+    run_root "export DEBIAN_FRONTEND=noninteractive"
+    run_root "apt update"
+    run_root "apt install -y gnupg2 lsb-release curl"
+    run_root "curl https://repo.percona.com/apt/percona-release_latest.$(lsb_release -sc)_all.deb -o percona-release_latest.$(lsb_release -sc)_all.deb"
+    run_root "dpkg -i percona-release_latest.$(lsb_release -sc)_all.deb"
+
+  fi
+}
+
 
 #########################################
-# Install PS
+# Install PS or PXC
 #########################################
-install_ps() {
+function install_packages()
+{
+  if [[ $VAR_MODE =~ ^ps$ ]]; then
+    VAR_MODE_STRING="Percona Server"
+    run_root "percona-release setup ps80"
+    PACKAGES_TO_INSTALL="${PACKAGES_TO_INSTALL} percona-server-server"
+  elif [[ $VAR_MODE =~ ^pxc$ ]]; then
+    VAR_MODE_STRING="Percona XtraDB Cluster"
+    run_root "percona-release setup pxc80"
+    PACKAGES_TO_INSTALL="${PACKAGES_TO_INSTALL} percona-xtradb-cluster"  
+  fi
 
-  msg "${GREEN}Starting ${NOFORMAT} installation of Percona Server"
-  SUDO=sudo
-	MYSQL_SERVICE_NAME=""
-	if [ -f /usr/bin/yum ]; then
-		MYSQL_SERVICE_NAME=mysqld
-		if [ ! -f /usr/bin/sudo ]; then
-			if [[ $(id -u) -eq 0 ]]; then
-				SUDO=""
-			else
-				yum install -y sudo
-			fi
-		fi
+  if check_command yum ; then
+    run_root "yum install -y ${PACKAGES_TO_INSTALL}"
+  else
+    run_root "apt-get install -y ${PACKAGES_TO_INSTALL}"
+  fi
+}
 
-		# Install Percona Server
-		${SUDO} yum install -y https://repo.percona.com/yum/percona-release-latest.noarch.rpm which &&
-		${SUDO} percona-release setup -y ps80 &&
-		${SUDO} yum install -y percona-server-server
-	else
-		MYSQL_SERVICE_NAME=mysql
-		if [ ! -f /usr/bin/sudo ]; then
-			if [[ $(id -u) -eq 0 ]];
-			then
-				SUDO=""
-			else
-				apt update
-				apt install -y sudo
-			fi
-		fi
-		# Install Percona Server
-		${SUDO} DEBIAN_FRONTEND=noninteractive apt update
-		${SUDO} DEBIAN_FRONTEND=noninteractive apt install -y gnupg2 lsb-release curl
-		${SUDO} curl https://repo.percona.com/apt/percona-release_latest.$(lsb_release -sc)_all.deb -o percona-release_latest.$(lsb_release -sc)_all.deb
-		${SUDO} dpkg -i percona-release_latest.$(lsb_release -sc)_all.deb
-		${SUDO} percona-release setup ps80
-		${SUDO} DEBIAN_FRONTEND=noninteractive apt install -y percona-server-server
+function start_server()
+{
+  # Start Server
+  if check_command mysqld
+  then
+    if check_command systemctl
+    then
+      run_root "systemctl start mysql"
+    elif check_command service
+    then
+      run_root "service mysql start"
+    fi
 
-	fi
+    # Check if mysqld is running
+    if ! mysqladmin -u root ping > /dev/null 2>&1;
+    then
+      [ ! "$(ls -A /var/lib/mysql)" ] && run_root mysqld --user=mysql --initialize-insecure
 
-	# Start Percona Server
-	if which mysqld > /dev/null 2>&1;
-	then
-		if which systemctl > /dev/null 2>&1;
-		then
-			${SUDO} systemctl start mysqld > /dev/null 2>&1;
-		elif which service > /dev/null 2>&1;
-		then
-			${SUDO} service mysqld start > /dev/null 2>&1;
-		fi
+      run_root "mysqld --user=mysql &"
+    fi
 
-		# Check if mysqld is running
-		if ! mysqladmin -u root ping > /dev/null 2>&1;
-		then
-			[ ! "$(ls -A /var/lib/mysql)" ] && ${SUDO} mysqld --user=mysql --initialize-insecure
+    for i in $(seq ${START_TIMEOUT});
+    do
+      if ! mysqladmin -u root ping > /dev/null 2>&1;
+      then
+        sleep 1;
+      else
+        break;
+      fi
+    done
+    
+    if [[ ${i} -ne ${START_TIMEOUT} ]];
+    then
+      clear
+      echo "${VAR_MODE_STRING} Installed!"
+      echo ""
+      echo "To connect to your server, type:"
+      echo "mysql -u root"
+      echo ""
+      exit 0
+    fi
+  fi
 
-			${SUDO} mysqld --user=mysql &
-		fi
-
-		for i in $(seq ${START_TIMEOUT});
-		do
-			if ! mysqladmin -u root ping > /dev/null 2>&1;
-			then
-				sleep 1;
-			else
-				break;
-			fi
-		done
-		
-		if [[ ${i} -ne ${START_TIMEOUT} ]];
-		then
-			echo "Percona Server Installed!"
-			echo ""
-			echo "To connect to your server, type:"
-			echo "mysql -u root"
-			echo ""
-	    msg "${GREEN}Completed ${NOFORMAT} installation of Percona XtraBackup"
-			exit 0
-		fi
-	fi
-
-	msg "${RED}FAILED ${NOFORMAT} instatlation of Percona XtraBackup"
-	exit 1
+  echo "${RED}FAILED: ${NOFORMAT}Error Installing ${VAR_MODE_STRING}"
+  exit 1
 } 
 
 ############################
@@ -210,6 +251,11 @@ main() {
 	if [ ${install_backup} ] ; then
 		install_pxb	
 	fi
+	install_repo_and_define_service
+	install_packages
+	clear
+	start_server
+	exit 0 
 }
 
 parse_params "${@}"
